---
$schema: http://json-schema.org/draft-07/schema#
$id: https://open-resource-discovery.org/spec-v1/interfaces/Configuration.schema.json#
title: Ord Configuration
description: |-
  The ORD configuration response will indicate that ORD is available for the given host and how to proceed with the discovery.

  Most notably, the ORD configuration will tell an ORD consumer which ORD documents are available and where/how they can be accessed.

  The configuration endpoint is a [Well-Known URI](https://tools.ietf.org/html/rfc8615#section-3) discovery mechanism.

  This JSON Schema describes the [ORD configuration interface](https://open-resource-discovery.org/spec-v1/interfaces/Configuration) of the [ORD specification](https://open-resource-discovery.org/).
type: object
properties:
  $schema:
    type: string
    format: uri-reference
    description: |-
      Optional URL to the ORD Configuration schema (defined as JSON Schema).
      If given, this enables code intelligence and validation in supported editors (like VSCode) and tools.
    anyOf:
      - type: string
        format: uri-reference
      - const: "https://open-resource-discovery.org/spec-v1/interfaces/Configuration.schema.json#"

  baseUrl:
    type: string
    format: uri
    description: |-
      Optional [base URL](../index.md#base-url) that can be used to resolve the relative URLs to the ORD Documents.

      The `baseUrl` MUST NOT contain a leading slash.

      If you do not provide this property, the base URL is assumed to be the URL of the config endpoint without `/.well-known/open-resource-discovery` suffix.
      This implies that either a `baseUrl` or only absolute URLs MUST be provided when no standardized well-known URI is used.
      If both a `baseUrl` and a well-known URI is provided, the explicit `baseUrl` takes precedence.
    pattern: ^http[s]?:\/\/[^:\/\s]+\.[^:\/\s\.]+(:\d+)?(\/[a-zA-Z0-9-\._~]+)*$
    examples:
      - "https://example-sap-system.com"
      - "https://sub.foo.bar.com"
      - "https://sub.foo.bar.com/api/v1"

  openResourceDiscoveryV1:
    "$ref": "#/definitions/OpenResourceDiscoveryV1"
additionalProperties: false
required:
  - openResourceDiscoveryV1
definitions:
  OpenResourceDiscoveryV1:
    type: object
    title: Ord V1 Support
    description: |-
      The existence of this version indicates that Open Resource Discovery is supported in Version 1.x
    x-ums-type: "ignore"
    properties:
      documents:
        type: array
        description: |-
          List of all ORD documents that can be retrieved.

          While it is possible to describe everything in one big ORD document, for bigger services/use cases it might be preferable to split the information into multiple documents.

          For more details how to implement this correctly, please refer to the [ORD configuration endpoint](../index.md#ord-configuration-endpoint) section and the [considerations on the granularity of ORD documents](../index.md#considerations-on-the-granularity-of-ord-documents).
        items:
          "$ref": "#/definitions/V1DocumentDescription"

      capabilities:
        "$ref": "#/definitions/V1Capabilities"

    additionalProperties: false

  ############################################################################################################

  V1DocumentDescription:
    type: object
    title: Ord V1 Document Description
    description: |-
      Describes an [ORD Document](../index.md#ord-document) that is available for pull transport consumption.
    x-ums-type: "ignore"
    properties:
      url:
        type: string
        format: uri-reference
        description: |-
          URL or relative URL to the ORD document (provided by an ORD document endpoint).

          It is RECOMMENDED to provide a relative URL (to `baseUrl`).
          If a `baseUrl` is given, the relative URLs will be resolved with it.

          If the URL is not relative to the system providing this information or no well-known URI is used,
          either the baseUrl or a full URL to the document MUST be provided.
        examples:
          - "/open-resource-discovery/v1/documents/example1"
          - "../../documents/example1"
          - "https://example.com/open-resource-discovery/v1/documents/example1"

      perspective: # HINT: Ensure this stays in sync with the Document.schema.yaml
        type: string
        x-introduced-in-version: "1.12.0"
        x-feature-status: beta
        description: |-
          With ORD it's possible to describe a system from a static or a dynamic [perspective](../index.md#perspectives) (for more details, follow the link).

          It is strongly RECOMMENDED to mark all static ORD documents with perspective `system-version`.

          It is RECOMMENDED to describe dynamic metadata in both static system-version perspective and additionally describe the system-instance perspective where it diverges from the static metadata.

          If not provided, this defaults to `system-instance`, which is the most precise description but also the most costly to replicate.

          Please read the [article on perspectives](../concepts/perspectives) for more explanations.
        oneOf:
          - const: "system-version"
            description: |-
              Describes the static [system-version](../index.md#system-version) perspective, usually known at deploy-time.

              If chosen, `describedSystemVersion`.`version` MUST be provided, too.

              This perspective describes how a system of a particular type and version generally look like.
              The latest system-version MAY also be interpreted as the [system-type](../index.md#system-type) perspective.
          - const: "system-instance"
            description: |-
              Describes the complete dynamic [system-instance](../index.md#system-instance) (tenant) perspective as known at run-time.
              This allows to also reflect tenant specific extensions, customizations and runtime configuration.

              If provided, it will completely override the static system-version perspective when metadata about system instances is requested.
          # - const: "system-instance-delta"
          #   description: |-
          #     TODO: As future optimization we could also provide this perspective, which only describes the actual difference between the system-instance and system-version perspective.

          #     If chosen, `describedSystemVersion`.`version` MUST be provided, too.
          - const: "system-independent"
            description: |-
              Describes content that is independent of [system-versions](../index.md#system-version) or [system-instances](../index.md#system-instance).
              This content is always static and has independent visibility and lifecycle from the systems in a particular landscape.
              The "system-independent" content MUST NOT be overridden via system-version or system-instance perspective metadata.

              Examples are: Vendors, products, globally aligned entity types, groups and group types (taxonomy), which are usually shared by multiple systems.
        default: "system-instance"
        examples:
          - "system-instance"

      systemInstanceAware:
        type: boolean
        description: |-
          Whether the information in the ORD document is **system-instance-aware**.
          This is the case when the provided ORD document potentially differs between **system instances** (e.g. due to multi-tenancy, configuration or extensibility).

          If a document is system-instance-aware, an ORD aggregator MUST fetch it for _each_ **system instance** (tenant), not just once per system type.

          This concept is now **deprecated** in favor of the more explicit `perspective` attribute.
          It is strongly RECOMMENDED to split metadata into separate documents for the different perspectives (static vs. dynamic).

          For a detailed explanation, see [perspectives concept page](../concepts/perspectives.md) or the [specification section](../index.md#perspectives).
        default: false
        x-deprecated-in-version: "1.12.0"
        x-deprecation-text: |-
          Please use `perspective` instead and split content of different perspectives into different ORD documents.
        examples:
          - true

      accessStrategies:
        type: array
        description: |-
          List of supported access strategies for retrieving the metadata from the ORD provider.

          An ORD Consumer/ORD Aggregator MAY freely choose any of the listed strategies.

        items:
          $ref: "#/definitions/AccessStrategy"
        minItems: 1

    additionalProperties: false
    required:
      - url
      - accessStrategies

  #/definitions/V1Capabilities"
  V1Capabilities:
    type: object
    title: Ord V1 Capabilities
    description: |-
      List of capabilities that are supported by the ORD provider.
    x-ums-type: "ignore"
    properties:
      selector:
        type: boolean
        default: false
        description: |-
          Whether the ORD provider supports the optional `select` parameter ([select parameter](../index.md#select-parameter)) for retrieving the ORD config and ORD documents.

  ############################################################################################################

  AccessStrategy:
    type: object
    title: Ord V1 Document Access Strategy
    description: |-
      Defines the [access strategy](../../spec-extensions/access-strategies/) for accessing the ORD documents from the ORD provider.
    x-ums-type: "ignore"
    properties:
      type:
        type: string
        description: |-
          Defines the authentication/authorization strategy through which the referenced ORD Documents can be accessed.
        anyOf:
          - type: string
            pattern: ^([a-z0-9]+(?:[.][a-z0-9]+)*):([a-zA-Z0-9._\-]+):(v0|v[1-9][0-9]*)$
            description: |-
              Any valid [Specification ID](../index.md#specification-id).
              If chosen, `customDescription` SHOULD be provided.
          - const: open
            description: |-
              The resource definitions are openly accessible and not protected via authentication or authorization.
              Please find a more detailed documentation [here](../../spec-extensions/access-strategies/open).
          - const: basic-auth
            description: |-
              The resource definitions are protected via generic basic auth.
              Please find a more detailed documentation [here](../../spec-extensions/access-strategies/basic-auth).
            x-introduced-in-version: "1.12.1"
          - const: custom
            description: |-
              If chosen, `customType` MUST be provided.
              If chosen, `customDescription` SHOULD be provided.
        examples:
          - open

      customType: &customType
        type: string
        description: |-
          If the fixed `type` enum values need to be extended, an arbitrary `customType` can be provided.

          MUST be a valid [Specification ID](../index.md#specification-id).

          MUST only be provided if `type` is set to `custom`.
        pattern: ^([a-z0-9]+(?:[.][a-z0-9]+)*):([a-zA-Z0-9._\-]+):v([0-9]+)$
        maxLength: 255
        examples:
          - "sap.xref:open-local-tenant-id:v1"

      customDescription: &customDescription
        type: string
        minLength: 1
        description: |-
          Human-readable description about how the access is set up, notated in [CommonMark](https://spec.commonmark.org/) (Markdown).

          MUST only be provided if `type` is set to `custom`.
        examples:
          - |-
            To set up the access to OData APIs, please refer to the [SAP Cloud for Customer OData API](https://help.sap.com/viewer/1364b70b9cbb417ea5e2d80e966d4f49/CLOUD/en-US) help pages.
    additionalProperties: false
    required:
      - "type"
    examples:
      - type: "open"
      - type: "custom"
        customType: "sap.xref:open-local-tenant-id:v1"
        customDescription: "Custom description how to use custom access strategy"
